### ISSUE TITLE
Exit status of grep

### ISSUE THREAD

**Issue by davide-acanfora** [RPi-Distro/raspberrypi-sys-mods#75]
From the latest **Raspberry Pi OS Lite** image, the content of `/boot/cmdline.txt` before running `firstboot` is:

```
console=serial0,115200 console=tty1 root=PARTUUID=544c6228-02 rootfstype=ext4 fsck.repair=yes rootwait quiet init=/usr/lib/raspberrypi-sys-mods/firstboot
```

If I am not wrong (according to [this](https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/5ce3ef2b7f377c23fea440ca9df0e30f3f8447cf/usr/lib/raspberrypi-sys-mods/firstboot#LL243C1-L245C3)) the string `quiet` is removed only if the string `splash` is found. However, given the file mentioned above `quiet` appears to be removed anyway, infact after first reboot the content of `cmdline.txt` becomes this:

```
console=serial0,115200 console=tty1 root=PARTUUID=544c6228-02 rootfstype=ext4 fsck.repair=yes rootwait
```

Knowing that the exit status of `grep` is **0** when a match is found and that such value is interpreted as a success in an `if` statement, shouldn't the negation be removed from the following line?

https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/5ce3ef2b7f377c23fea440ca9df0e30f3f8447cf/usr/lib/raspberrypi-sys-mods/firstboot#L243

What am I missing?

**Comment by MichaIng** [comment]
The `quiet` flag is removed only if the `splash` flag is **NOT** found, and I guess this is intended:
- If `splash` is set, you want a splash screen and not kernel logs, hence it makes sense to leave the `quiet` flag in place.
- If no splash screen is wanted, it makes sense to show kernel logs instead, otherwise you would just see a blinking indicator at the top left of a black screen.
