### ISSUE TITLE
Recent removal of /boot/cmdline.txt link to /boot/firmware/cmdline.txt

### ISSUE THREAD

**Issue by framps** [RPi-Distro/raspberrypi-sys-mods#88]
[This commit](https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/c62cf1a12f4e422c855f7e2fcb39e9cadcb5459b) replaces the link from /boot/cmdline.txt to /boot/firmware/cmdline.txt with some informational text the file was moved.

What's the rational to remove this link? From a backward compatible point of view the link was the perfect way to make sure all tools which either read of modify /boot/cmdline.txt also will work with Bookworm.

From a coding perspective it's not a big deal to update the tools. But what about users of the tools? Hopefully the tools now fail with an error message but what about tools which silently finish but don't do their job any more? For example rpi-clone now doesn't create a bootable clone any more and rpi-clone users will not become aware the clone doesn't boot any more.

**Comment by popcornmix** [comment]
I believe some editors will replace the symlink with an actual file at `/boot/cmdline.txt` (which will be ignored as far as booting goes).

The symlink has been removed to avoid the confusion that can cause.

**Comment by MichaIng** [comment]
No (command-line) editor that I am aware of. But `sed -i` does so, if not used with `--follow-symlinks` flag. So indeed the symlink is dereferenced by a lot of 3rd party scripts/installers (like for LCDs, HATs etc) which often use `sed` to add device tree overlays and stuff.

The one way of the other, moving the boot partition mount point was a breaking change that will cause a lot of short- and mid-term trouble.

While the original `rpi-clone` is dead since years, some forks have adjusted, using `realpath` and/or `sed --follow-symlinks`, e.g.: https://github.com/framps/rpi-clone/commits/master/

**Comment by framps** [comment]
> some forks have adjusted

Yes, and now have to adjust again :-(. There is now a [second fix](https://github.com/framps/rpi-clone/commit/e82f586170af769f6d1090f5508120eb36b9a997) for rpi-clone available already which will be merged into master if there is no other comment on the fix the next week. But nevertheless this second fix wouldn't be required if the link was been kept. Not sure if other tools also have to modify their code now a second time.

**Comment by MichaIng** [comment]
Ah, I recognised just now that its your fork 😄. I guess the solution to check whether `/boot/firmware` exists, or `/boot/firmware/(config|cmdline).txt` in particular and then use the correct absolute path in the first place (e.g. as a variable), is best that can be done to avoid all possible issues: the symlink is not dereferenced and it does not depend on the symlink either.

**Comment by framps** [comment]
As I wrote it's not a big deal to update the code for rpi-clone :-). But I'm mainly concerned about any other tools which depend of the link of /boot/cmdline.txt and now will either fail or silently don't do their job any more.

**Comment by pelwell** [comment]
There have been enough instances of people seeing confusing symptoms that turned out to be due to editing a real, non-symlink /boot/config.txt to make this seem like a good idea to me. If there _is_ an editor which breaks the symlink then it is likely to affect more people (and probably less proficient people) than this change.

**Comment by MichaIng** [comment]
To avoid silent failures, the immutable flag could be added. But this flag is also a hurdle for people who do not know about it, e.g. if someone wants to remove the file, and even root cannot do it without removing the flag first.

**Comment by XECDesign** [comment]
> To avoid silent failures, the immutable flag could be added. But this flag is also a hurdle for people who do not know about it, e.g. if someone wants to remove the file, and even root cannot do it without removing the flag first.

Yeah, that's the exact reason I didn't do that. It's a feature many people don't know about and if they find that there's a file that they seemingly can't do anything with, it might cause even more confusion.

Anyway, closing the issue since it has been answered by others already.

**Comment by sassanh** [comment]
You can see the impact in action here ;-)
https://github.com/ubopod/ubo-app/actions/runs/8460684596/job/23179353095#step:9:1760
